import { Card } from "@/components/ui/card";

export default function Privacy() {
  return (
    <main className="min-h-screen bg-slate-50 p-8 text-slate-900">
      <div className="mx-auto max-w-4xl">
        <p className="mb-3 font-semibold text-blue-700">Belentani · Información de privacidad</p>
        <h1 className="text-4xl font-bold">Política de Privacidad</h1>
        <p className="mt-3 text-slate-600">Borrador operativo. Debe completarse con la identidad jurídica, domicilio, registro y canales reales del responsable antes del lanzamiento comercial.</p>

        <div className="mt-8 space-y-6">
          <Card className="p-6"><h2 className="text-2xl font-bold">1. Responsable</h2><p className="mt-3 text-slate-700">Responsable: <strong>[nombre o razón social real]</strong>. Domicilio: <strong>[domicilio]</strong>. Contacto de privacidad: <strong>[correo real]</strong>. No se debe publicar un DPD ficticio: si la designación de delegado es obligatoria o se decide voluntariamente, se indicará la persona o entidad y su canal efectivo.</p></Card>
          <Card className="p-6"><h2 className="text-2xl font-bold">2. Datos tratados</h2><p className="mt-3 text-slate-700">La plataforma puede tratar identidad, correo, teléfono y localidad, información profesional introducida para el CV, fotografía opcional, documentos generados, datos técnicos de seguridad y registros de solicitudes de privacidad. Stripe u otros proveedores de pago tratan los datos de pago en sus propios sistemas; Belentani no debe almacenar números completos de tarjeta ni CVV.</p></Card>
          <Card className="p-6"><h2 className="text-2xl font-bold">3. Finalidades y bases jurídicas</h2><p className="mt-3 text-slate-700">Prestar la generación de CV y guardar documentos a petición del usuario: ejecución del servicio. Mantener seguridad, prevenir abuso y atender incidencias: interés legítimo, documentado y ponderado. Cumplir obligaciones fiscales o legales: obligación legal cuando proceda. Marketing, analítica no necesaria y cookies no esenciales: consentimiento separado y revocable.</p></Card>
          <Card className="p-6"><h2 className="text-2xl font-bold">4. IA, proveedores y transferencias</h2><p className="mt-3 text-slate-700">Los datos introducidos pueden enviarse al proveedor LLM configurado para generar el contenido. Antes del lanzamiento deben identificarse por nombre todos los proveedores, sus ubicaciones, subencargados, períodos de conservación, garantías de transferencias internacionales y contratos de encargo. No se utilizarán CVs para entrenar modelos salvo consentimiento válido y separado o base jurídica aplicable.</p></Card>
          <Card className="p-6"><h2 className="text-2xl font-bold">5. Conservación y eliminación</h2><p className="mt-3 text-slate-700">Los documentos se ocultan al solicitar la eliminación y existe una purga programable para solicitudes vencidas. El responsable debe activar y supervisar el job de purga, eliminar también los objetos asociados del almacenamiento cuando sea posible y documentar las excepciones legales de conservación. No se debe afirmar que el borrado es inmediato o total si el proceso no se ha ejecutado y verificado.</p></Card>
          <Card className="p-6"><h2 className="text-2xl font-bold">6. Derechos</h2><p className="mt-3 text-slate-700">Puedes solicitar acceso, rectificación, supresión, limitación, oposición y portabilidad, así como retirar consentimientos. El panel permite descargar una copia de los datos disponibles, solicitar eliminación y registrar una rectificación por categoría; para datos o copias que no aparezcan, escribe al contacto real de privacidad. Se responderá dentro de los plazos del RGPD, previa verificación proporcional de identidad.</p></Card>
          <Card className="p-6"><h2 className="text-2xl font-bold">7. Seguridad y brechas</h2><p className="mt-3 text-slate-700">La aplicación utiliza OAuth, cookies HttpOnly, HTTPS del entorno de alojamiento, cabeceras de seguridad, límites de solicitudes, validación de entradas, control de propiedad de documentos y re-procesado de imágenes. El cifrado aplicado a cada campo y la configuración de claves deben verificarse separadamente; esta página no afirma cifrado en reposo total. Las brechas se evaluarán y, cuando proceda, se notificarán a la autoridad competente en el plazo legal y a las personas afectadas cuando exista alto riesgo.</p></Card>
          <Card className="p-6"><h2 className="text-2xl font-bold">8. Cookies</h2><p className="mt-3 text-slate-700">Actualmente se pretende usar únicamente cookies necesarias para sesión y seguridad. No deben activarse analítica, publicidad ni cookies no esenciales antes de obtener consentimiento granular. El banner debe permitir aceptar, rechazar y configurar con igual facilidad, y conservar prueba de la elección.</p></Card>
          <Card className="p-6"><h2 className="text-2xl font-bold">9. Reclamaciones</h2><p className="mt-3 text-slate-700">Puedes reclamar ante la <a className="text-blue-700 underline" href="https://www.aepd.es/" target="_blank" rel="noreferrer">AEPD</a> o, cuando sea competente, ante la <a className="text-blue-700 underline" href="https://apdcat.gencat.cat/" target="_blank" rel="noreferrer">APDCAT</a>. El responsable debe completar antes del lanzamiento su identidad, domicilio y canal de reclamaciones.</p></Card>
        </div>
      </div>
    </main>
  );
}
